- proxy/server.py
Here is a sample output for backup switch:
"TEMSA--1624171-00-E--TG121161002JDY": {
"ISLAND_FreqL1_Load": 60.010000000000005,
"ISLAND_FreqL1_Main": 60.010000000000005,
"ISLAND_FreqL2_Load": 60.0,
"ISLAND_FreqL2_Main": 60.010000000000005,
"ISLAND_FreqL3_Load": 0.0,
"ISLAND_FreqL3_Main": 0.0,
"ISLAND_GridConnected": true,
"ISLAND_GridState": "ISLAND_GridState_Grid_Compliant",
"ISLAND_L1L2PhaseDelta": -180.0,
"ISLAND_L1L3PhaseDelta": -256.0,
"ISLAND_L1MicrogridOk": true,
"ISLAND_L2L3PhaseDelta": -256.0,
"ISLAND_L2MicrogridOk": true,
"ISLAND_L3MicrogridOk": false,
"ISLAND_PhaseL1_Main_Load": 0.0,
"ISLAND_PhaseL2_Main_Load": 0.0,
"ISLAND_PhaseL3_Main_Load": -256.0,
"ISLAND_ReadyForSynchronization": true,
"ISLAND_VL1N_Load": 123.0,
"ISLAND_VL1N_Main": 123.0,
"ISLAND_VL2N_Load": 123.5, …
> Add support for backup switch.

- proxy/Dockerfile
- proxy/server.py
- proxy/transform.py
- proxy/web/customize.js
Hello,
This PR adds support to the proxy feature of pypowerwall to proxy access to the Powerwall web interface and customize it's appearance. 
This lets you run the proxy on a local network and create iframe widgets for displays like Dakboard.
> Pass through Powerwall Web interface and customize for iframe displays

- proxy/web/black.js
- proxy/web/clear.js
- proxy/web/dakboard.js
- proxy/web/grafana.js
- proxy/web/white.js
Sometimes when embedding in an iframe, the vertical scrollbars are visible.
This patch hides the scrollbars for all styles.
Before:
After:
> remove scrollbars from web view

- proxy/server.py
The current code always binds to 0.0.0.0.  This adds support to specify binding (for example) to 127.0.0.1 to ensure the proxy is only accessible via localhost.
Example:
`export PW_BIND_ADDRESS=127.0.0.1;python ./server.py`
> Support specifying a bind address

- README.md
I've created a port for pypowerwall to make installation easier for FreeBSD users.  Add instructions on how to use it.
> Add FreeBSD-specific installation instructions

- pypowerwall/__init__.py
Added `SystemTransitionToIsland` and `SystemIslandedReady` to map, as these can be returned when transitioning to off-grid (more details in issue #7 )
> Add grid_status responses for syncing to off-grid

- proxy/README.md
- proxy/server.py
- pypowerwall/__init__.py
Implemented the use of HTTP persistent connections for API requests by default (refer issue #20)
- Requests to Gateway will now re-use persistent http connections which reduces load and increases response time
- Default connection `poolmaxsize=10` to align with Session object defaults. Note: pool use applies to multi-threaded use of pyPowerwall only, e.g. as with the pyPowerwall Proxy Server
- Added env `PW_POOL_MAXSIZE` to proxy server to allow this to be controlled (persistent connections disabled if set to zero)
- Added env `PW_TIMEOUT` to proxy server to also allow timeout on requests to be adjusted
- For release prep, pyPowerwall version changed to v0.6.0 and proxy version to t17 (release notes still required)
> Use HTTP persistent connections for API requests

- tools/set-mode.py
- tools/set-reserve.py
Revised error handling of SITE_DATA request due to issues noted in [#12](https://github.com/jasonacox/Powerwall-Dashboard/issues/12#issuecomment-1380981134) when multiple sites are linked to the Tesla account.
As the SITE_DATA request is only used to retrieve the current system time from the Powerwall, this has been revised so if any exception occurs when trying to fetch this, the script will no longer exit.
> Revise error handling of SITE_DATA request

- README.md
Adding some additional error messages discovered in the dashboard
> Additional error messages

- README.md
I lost solar production yesterday and this project was very helpful in checking the internal state, since there were no errors displayed in the Tesla app or local UI.
My alerts for PVS are
"alerts": [
"PVS_a036_PvArcLockout",
"PVS_a058_MciOpenOnFault",
"PVS_a059_MciOpen"
]
PVS_a036_PvArcLockout is not documented yet so I'm adding it in case it helps anyone. Last month a similar issue happened and Tesla came out and replaced MCIs
> add alert PVS_a036_PvArcLockout

- RELEASE.md
- proxy/README.md
- proxy/RELEASE.md
- proxy/server.py
- proxy/web/grafana-dark.js
This PR updates the proxy to include a `grafana-dark` style for `PW_STYLE`.  This is to accommodate placing as iframe in newer Grafana versions (e.g. v9.4.14) while matching the background. See https://github.com/jasonacox/Powerwall-Dashboard/discussions/371.
Also includes updates to documentation for environmental variable explanations.
> v0.6.2b - Proxy Grafana Support for Dark Mode

- README.md
- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/scan.py
* Added scan detection for new Powerwall 3 systems. API discovery is still underway so pypowerwall currently does not support Powerwall 3s. See https://github.com/jasonacox/Powerwall-Dashboard/issues/387
```
$ python3 -m pypowerwall scan
pyPowerwall Network Scanner [0.6.3]
Scan local network for Tesla Powerwall Gateways
Your network appears to be: 10.0.1.0/24
Enter Network or press enter to use 10.0.1.0/24: 
Running Scan...
Host: 10.0.1.2 ... OPEN - Not a Powerwall
Host: 10.0.1.5 ... OPEN - Found Powerwall 3 [Currently Unsupported]
Host: 10.0.1.8 ... OPEN - Not a Powerwall
Host: 10.0.1.9 ... OPEN - Found Powerwall 3 [Currently Unsupported]
Done                           
Discovered 2 Powerwall Gateway
10.0.1.5 [Powerwall-3] Firmware Currently Unsupported - See …
```
> v0.6.3 Powerwall 3 Detection

- README.md
- RELEASE.md
- proxy/RELEASE.md
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/cloud.py
This adds the option to set file path for cloud auth (`.pypowerwall.auth`) and site (`.pypowerwall.site`) cache files:
* API - The initializer now has `authpath` which defaults to current directory (`authpath=""`)
* Proxy - An environmental variable `PW_AUTH_PATH` is added which defaults to current directory.
This also adds the option to specify the energy site ID (`siteid`):
* API - The  initializer now has `siteid` which defaults to None.
* Proxy - The existing environmental variable `PW_SITEID` is available to set the `siteid`.
This will provide more flexibility to run the pypowerwall proxy in a container for cloud mode support.
> v0.7.2 - Add cloud mode configuration setting

- RELEASE.md
- proxy/Dockerfile
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/__main__.py
- pypowerwall/cloud.py
* Setup will now check for `PW_AUTH_PATH` environmental variable to set the path for `.pypowerwall.auth` and `.pypowerwall.site`
* Proxy t37 - Move signal handler to capture SIGTERM when proxy halts due to config error. This ensures a containerized proxy will exit without delay when stopping or restarting the container.
> v0.7.3 - Cloud Mode Setup

- README.md
- RELEASE.md
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/__main__.py
- pypowerwall/cloud.py
- pypowerwall/scan.py
This release adds the ability to use a Bearer Token for auth for local Powerwall gateway API calls. This is selectable by defining `authmode='token'` in the initialization. The default mode uses the existing `AuthCookie` and `UserRecord` method.
```python
import pypowerwall
pw = pypowerwall.Powerwall(HOST, PASSWORD, EMAIL, TIMEZONE, authmode="token")
```
This could potentially help with Issue #57 (untested)
> Add Bearer Token Auth

- RELEASE.md
- proxy/Dockerfile
- pypowerwall/__init__.py
- pypowerwall/__main__.py
- pypowerwall/cloud.py
- pypowerwall/scan.py
* Added optional email address argument to Cloud Mode setup (`python -m pypowerwall setup -email=<email>`) to streamline Powerwall-Dashboard setup script.
* Updated network scanner output to advise Powerwall 3 is supported in Cloud Mode.
> v0.7.5 - Cloud Mode Setup

- RELEASE.md
- proxy/Dockerfile
- proxy/RELEASE.md
- proxy/server.py
- pypowerwall/__init__.py
- web/index.html
This PR fixes bug in pypowerwall related to API calls and 404 HTTP status codes handling.
Powerwall Firmware version 23.44.0 has eliminated /api/devices/vitals resulting in a 404 response from the Powerwall Gateway (TEG) when this is requested. There is a bug in the pypowerwall code that will treat this 404 like an authentication failure which will result in attempts to log in over and over, eventually hitting the rate limit. This is especially impactful for those using the proxy for things like Powerwall-Dashboard as the rate limit will prohibit other data gathering.
Related issue: https://github.com/jasonacox/pypowerwall/issues/57
Closes #65
> Fix 404 handling #65 #57

- RELEASE.md
- proxy/Dockerfile
- proxy/RELEASE.md
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/__main__.py
- pypowerwall/scan.py
* Proxy: Use /api/system_status battery blocks data to augment /pod and /freq macro data APIs. 
This update will help address some of the data lost with the removal of the `vitals` data starting with Firmware 23.44.0 as raised in https://github.com/jasonacox/Powerwall-Dashboard/discussions/402. 
* Network Scanner: Improve network scan speed by scanning multiple hosts simultaneously. The number of hosts to scan simultaneously can be adjusted using the optional `-hosts=` argument (default = 30, maximum = 100), e.g. `python -m pypowerwall scan -hosts=50`
> v0.7.7 - Battery Data and Network Scanner

- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/cloud.py
While Tesla is trying to figure out how to properly set up my two-gateway and three-powerwall system, they created a blank Site on my account with no devices attach. In this scenario pypowerwall will crash trying to display information about sites during the site selection menu creation.
This patch just skips those if that fails. I suspect you might want another way of fixing it, but sharing this for discussion. It does work in the case I'm seeing right now (I have 2 sites at the moment, including this bogus one).
Photo of Tesla app for context attached.
> ignore sites that are not complete set up

- RELEASE.md
- pypowerwall/__init__.py
Hi,
I am using your library in my home stackstorm-based automation actions/workflows and needed to move the cache file outside the "current directory" of the action runners for safety and security. Had to extend your class and override the init, but then I thought to try to get this little change to upstream, so here it is. Hope you will accept this PR. Thanks!
> Allow customization of the cachefile location and name

- RELEASE.md
- pypowerwall/__init__.py
This will utilize the /api/solar_powerwall endpoint to populate the alerts array if devices (through vitals) are not present. Let me know if you want it simplified to not include the outer 'if'. I included it for clarity, to show the distinct paths, but it can also be simplified if needed (since it won't loop through devices that aren't present).
I also only used the fallback if alertsonly was true, since we don't have device specific information in that setup.
This should be automatically picked up by the alerts/pw endpoint since the format is the same.
I tested it locally using the /alerts endpoint, but might be good to validate that it still uses vitals if they are present (it should). I am on the later firmware where it's no longer present (23.44). 
Let me know if you'd like anything …
> Adding alternate alerts when vitals not present

- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/cloud.py
Adds logic to pull string data from `/api/solar_powerwall` API if vitals data is not available.
This applies to Firmware > 23.44 and owners of Powerwall+ systems (integrated inverters). The API seems to only return the string attached tot he first Powerwall+ system. This will be changed out if we discover a way to get all strings.
> Use solar_powerwall for string data

- RELEASE.md
- proxy/RELEASE.md
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/local/pypowerwall_local.py
* This adds a 5m cooldown for 503 Service Unavailable errors from APIs - As seen with `/api/solar_powerwall` in https://github.com/jasonacox/Powerwall-Dashboard/pull/462 
* Proxy: Adds list of API that have been removed and ignores them (currnetly only `/api/customer/registration`) as reported  in https://github.com/jasonacox/Powerwall-Dashboard/pull/462
> Handle 503 Errors and Disabled Powerwall APIs

- RELEASE.md
- proxy/README.md
- proxy/RELEASE.md
- proxy/requirements.txt
- proxy/server.py
- pypowerwall/__init__.py
* Added additional error handling logic to clean up exceptions #81
* Proxy: Fix `/pod` API to add `time_remaining_hours` and `backup_reserve_percent` for cloud mode.
* Added control APIs to set backup reserve and operating mode settings. Requires setting `PW_CONTROL_SECRET`. Use with caution! Closes #79
```bash
curl http://localhost:8675/control/mode?token=$PW_CONTROL_SECRET&value=self_consumption
curl http://localhost:8675/control/reserve?token=$PW_CONTROL_SECRET&value=20
curl http://localhost:8675/control/mode?token=$PW_CONTROL_SECRET
curl http://localhost:8675/control/reserve?token=$PW_CONTROL_SECRET
```
> V0.8.3 - Control APIs

- README.md
- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/__main__.py
- pypowerwall/cloud/pypowerwall_cloud.py
- pypowerwall/fleetapi/pypowerwall_fleetapi.py
* Fix bug in time_remaining_hours() and convert print statements in FleetAPI to log messages.
* Fix CLI bug related to `site_id` as raised by @darroni in https://github.com/jasonacox/pypowerwall/issues/93
* Add CLI option for local mode to get status:
```bash
python -m pypowerwall get -host 10.1.2.3 -password 'myPassword'
```
Closes #93
> v0.9.1 Bug Fixes and Updates

- README.md
- RELEASE.md
- proxy/RELEASE.md
- proxy/requirements.txt
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/__main__.py
- pypowerwall/tedapi/__init__.py
- pypowerwall/tedapi/__main__.py
- requirements.txt
- setup.py
* Update `setup.py` to include dependencies on `protobuf>=3.20.0`.
* Add TEDAPI `connect()` logic to better validate Gateway endpoint access.
* Add documentation for TEDAPI setup.
* Update CLI to support TEDAPI calls.
* Proxy t60 - Fix edge case where `/csv` API will error due to NoneType inputs.
* Add TEDAPI argument to set custom GW IP address.
```bash
python3 -m pypowerwall tedapi
python3 -m pypowerwall.tedapi GWPASSWORD
python3 -m pypowerwall.tedapi --debug
python3 -m pypowerwall.tedapi --gw_ip 192.168.91.1 --debug
```
Reference: #97
> v0.10.3 - TEDAPI Connect

- RELEASE.md
- proxy/RELEASE.md
- proxy/requirements.txt
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
- pypowerwall/tedapi/pypowerwall_tedapi.py
* Fix for TEDAPI "full" (e.g. Powerwall 3) mode, including `grid_status` bug resulting in false reports of grid status, `level()` bug where data gap resulted in 0% state of charge and `alerts()` where data gap from tedapi resulted in a `null` alert.
* Add TEDAPI API call locking to limit load caused by concurrent polling.
* Proxy - Add battery full_pack and remaining energy data to `/pod` API call for all cases.
> v0.10.5 - Minor Fixes

- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/fleetapi/fleetapi.py
* FleetAPI - Add `get_history()` and `get_calendar_history()` to return energy, power, soe, and other history data.
```python
import pypowerwall
pw = pypowerwall.Powerwall(host=PW_HOST, email=PW_EMAIL, fleetapi=True)
pw.client.fleet.get_calendar_history(kind="soe")
pw.client.fleet.get_history(kind="power")
```
> Add power history retrieval to FleetAPI

- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/tedapi/pypowerwall_tedapi.py
- pypowerwall/tedapi/stubs.py
* Add computed voltage and current to `/api/meters/aggregates` using system data from TEDAPI status payload.
> Add computed voltage and current to aggregates from TEDAPI status data

- README.md
- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/__main__.py
- pypowerwall/cloud/pypowerwall_cloud.py
- pypowerwall/fleetapi/fleetapi.py
- pypowerwall/fleetapi/pypowerwall_fleetapi.py
- pypowerwall/local/pypowerwall_local.py
* Add functions and command line options to allow user to get and set grid charging and exporting modes (see https://github.com/jasonacox/pypowerwall/issues/108).
* Supports FleetAPI and Cloud modes only (not Local mode)
```bash
python3 -m pypowerwall setup # or fleetapi
python3 -m pypowerwall get
python3 -m pypowerwall set -gridcharging on
python3 -m pypowerwall  set -gridcharging off
python3 -m pypowerwall set -gridexport pv_only
python3 -m pypowerwall set -gridexport battery_ok
python3 -m pypowerwall set -gridexport never
```
```python
import pypowerwall
PW_HOST=""
PW_EMAIL="my@example.com"
pw = pypowerwall.Powerwall(host=PW_HOST, email=PW_EMAIL, fleetapi=True)
pw.get_grid_charging()
pw.get_grid_export()
pw.set_grid_charging("on") # set grid charging mode (on or off) …
```
> Add Grid Control Functions 

- .gitignore
- RELEASE.md
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
* Add polling of Powerwall 3 Devices to pull in PW3 specific string data, capacity, voltages, frequencies, and alerts. 
* This adds mock TEPOD, PVAC and PVS compatible payloads available in vitals().
You can test the updated code by editing the `powerwall.yml` file and changing the image to the beta version (jasonacox/pypowerwall:0.11.0t64-beta3): [[UPDATED]]
```yml
pypowerwall:
image: jasonacox/pypowerwall:0.11.0t64-beta3
container_name: pypowerwall
```
Restart:
```bash
./compose-dash.sh up -d
docker logs pypowerwall -f
```
Some URLs to check: 
* http://localhost:8675/vitals 
* http://localhost:8675/help (verify pw3 shows True) 
* http://localhost:8675/tedapi/components
* http://localhost:8675/tedapi/battery  
Discussion link: https://github.com/jasonacox/Powerwall-Dashboard/discussions/3 …
> Add PW3 Vitals

- proxy/RELEASE.md
- proxy/server.py
* Add PW_NEG_SOLAR config option and logic to remove negative solar values for `/aggregates` and `/csv` APIs
* Update http://pypowerwall:8675/stats and http://pypowerwall:8675/help to show config data
Reference: 
https://github.com/jasonacox/Powerwall-Dashboard/issues/543#issuecomment-2480684273
> Remove Negative Solar Values [Option]

- RELEASE.md
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
* TEDAPI: Add `get_device_controller()` to get device data which includes Powerwall THC_AmbientTemp. 
* Updated `vitals()` to include Powerwall temperature data using new `get_device_controller()` function.
* Proxy Updated to t66 to include API response for /tedapi/controller.
Credit to @ygelfand (and [go-powerwall proxy](https://github.com/ygelfand/go-powerwall)) for discovery and reported in https://github.com/jasonacox/Powerwall-Dashboard/discussions/392#discussioncomment-11360474
> Add Powerwall Temps

- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/__main__.py
- pypowerwall/scan.py
- Returns a list of the discovered devices for use as a utility function.
- Ability to silence output for use as a utility.
- Improve performance of multi-threaded scan by using a Queue.
- Switch to "f" strings for interactive output.
- General code flow improvements and encapsulation.
- Switch to more generalized wording. Not all Tesla Energy Gateways are Powerwalls anymore. Add ability to work with standalone inverters.
I am building a utility that I plan to run periodically to collect string data from my standalone Tesla inverters. Because this requires local LAN IP access, there is a possibility that  the IP address will change on the LAN (especially if it's on wifi). Therefore, my utility should do a quick scan of the network every time it reports data. Thus, I needed something that …
> Large-scale refactor of scan function

- RELEASE.md
- proxy/RELEASE.md
- proxy/requirements.txt
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
- pypowerwall/tedapi/pypowerwall_tedapi.py
* Fix bug in cache expiration timeout code that was not honring pwcacheexpire setting. Raised by @erikgiesele in https://github.com/jasonacox/pypowerwall/issues/122 - PW_CACHE_EXPIRE=0 not possible? (Proxy)
* Add WARNING log in proxy for settings below 5s.
* Change TEDAPI config default timeout from 300s to 5s and link to pwcacheexpire setting.
Closes #122
> v0.12.2 - TEDAPI Cache Expiration Fix

- pypowerwall/tedapi/__init__.py
The hard-coded 192.168.91.1 for the Tesla Inverters internal endpoint doesn't always work if you're using NAT. Change this to be compatible with the rest of the file and to enable this use-case.
Tested with a custom NAT configuration to verify that the firmware loads properly with a non-192.168.91.1 host.
> Change GW_IP to self.gw_ip

- proxy/RELEASE.md
- proxy/requirements.txt
- proxy/server.py
Minor update to bump library version and provide expanded data for simple clients via `/csv/v2` API endpoint. 
* pyPowerwall v0.12.3 - Adds Custom GW IP for TEDAPI. 
* Add new API /csv/v2 which extends /csv by adding grids status (1/0) and battery reserve (%)setting:
```python
-76.00,1114.25,360.00,780.00,96.51,1,20
```
> Update proxy for v0.12.3 and add /csv/v2 API support

- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
- pypowerwall/tedapi/pypowerwall_tedapi.py
In certain TEDAPI edge cases the grid status was not correct. This fixes it so that "SystemConnectedToGrid" is the only alert that appears if the Tesla alerts API contains such a thing. It also removes risk of duplicates and normalizes this particular alert.
> Improvements to grid status connected

- RELEASE.md
- proxy/requirements.txt
- pypowerwall/__init__.py
- pypowerwall/tedapi/pypowerwall_tedapi.py
While doing some testing I saw this error:
```
if "SystemConnectedToGrid" in alerts:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```
I'm not sure what triggered it, but it's an edge case that needs to be fixed.
> Alerts in extract_grid_status can be None. Block this edge case.

- pwsimulator/README.md
- pwsimulator/control.html
- pwsimulator/stub.py
Working on the power flow animation, I wanted an easy way to adjust the simulator parameters without having to stop/restart it. I added in some test commands, like `curl -k https://localhost/test/battery-percentage/100.0`(set the battery to 100%), and some sample scenarios like `curl -k http://localhost/test/scenario/nighttime-outage` (disconnected from grid, powering from the battery). There's also a basic UI for sending those commands at https://localhost/test/
For funsies I made an external UI for this (https://github.com/mccahan/pypowerwall-simulator-control), but not including that code here.
> Add simulator test commands

- proxy/HELP.md
- proxy/RELEASE.md
- proxy/server.py
Playing around with some widget stuff, the CSV endpoints are very convenient but it's helpful to be able to get them with headers. I put it in as a query string and made sure it won't affect any existing URL calls. I switched the order around starting on line ~386 because otherwise `self.path.startswith('/csv')` would match `/csv/v2` as well
http://localhost:8675/csv/v2?headers
http://localhost:8675/csv?headers
> Add option to get CSV headers

- pypowerwall/api_lock.py
- pypowerwall/tedapi/__init__.py
- Using a dictionary with an api lock is not thread safe. Given that this is frequently called from the proxy, a more thread safe option is appropriate, especially because I am in the process of modifying the proxy to call multiple gateways.
- A large amount of the "changes" are simply indenting existing lines for the "with" statement that the api lock uses.
- Update some typing
- Switch to enumerate instead of manually incrementing indicies.
- Using my Raspberry PI. This has been working well for about a week.
> Add thread locking to TEDAPI

- README.md
- examples/network_route.py
When using the TEDAPI over a LAN from Linux, it's critical to add a network route. However, I wanted to do this programmatically from Python before calling pypowerwall to get data.
This adds what I've learned and two example functions showing how to do just that.
> Improve route documentation and add example

- RELEASE.md
- proxy/requirements.txt
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
- Misc code cleanup in adjacent areas.
- Of note: No need to change the "code" parameter. The value field is apparently not validated against it.
Works on my dual-inverter setup with 2x 7.6 kW Tesla inverters.
> Add fan speeds to TEDAPI monitoring

- proxy/RELEASE.md
- proxy/server.py
* Add routes for fan speeds: `/fans` and `/fans/pw` (simple enumerated values for dashboard)
> Add fan speed routes and update proxy version to t71

- proxy/RELEASE.md
- proxy/server.py
Issue #162: add /pw/XXX endpoints to expose Powerwall() API methods as JSON-returning endpoints
> Issue #162: add /pw/XXX endpoints to expose Powerwall() API methods

- RELEASE.md
- proxy/RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
v0.12.10 - Power Flow and Other Fixes
* Catch error condition when components payload is empty or malformed. Bug in extract_fan_speeds() reported by by @jgleigh in jasonacox/Powerwall-Dashboard#392 and https://github.com/jasonacox/pypowerwall/issues/167
Closes #167
> Fix bug in extract_fan_speeds() 

- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
* Fix error handling in component data handling in TEDAPI.
Addresses error as seen in logs:
-------------------------------------
AttributeError: 'NoneType' object has no attribute 'get'
----------------------------------------
Traceback (most recent call last):
File "/usr/local/lib/python3.10/socketserver.py", line 683, in process_request_thread
self.finish_request(request, client_address)
File "/usr/local/lib/python3.10/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/local/lib/python3.10/socketserver.py", line 747, in __init__
self.handle()
File "/usr/local/lib/python3.10/http/server.py", line 433, in handle
self.handle_one_request()
File "/usr/local/lib/python3.10/http/server.py", line 421, in handle_one_request
method() …
> Fix error handling in  component data handling in TEDAPI

- proxy/RELEASE.md
- proxy/server.py
For details see: https://github.com/jasonacox/pypowerwall/discussions/163
New `/json` endpoint that returns the following values as JSON:
`/api/meters/aggregates` for `.solar.instant_power`
`/api/meters/aggregates` for `.battery.instant_power`
`/api/meters/aggregates` for `.load.instant_power`
`/api/meters/aggregates` for `.site.instant_power`
`/soe` for `.percentage`
`/pod` for `.time_remaining_hours`
Tested with my own Powerwall 2.
> Simple vitals endpoint for external integration

- proxy/RELEASE.md
- proxy/server.py
I have added the following values to the `/json` endpoint:
`nominal_full_pack_energy`
`nominal_energy_remaining`
`strings`
`nominal_full_pack_energy `and `nominal_energy_remaining `are tested.
I cannot test the `strings `because I have a SolarEdge inverter.
> Additional values /json endpoint

- pypowerwall/tedapi/__init__.py
- pypowerwall/tedapi/pypowerwall_tedapi.py
`METER_X` and `METER_Y` are specific to a Tesla electrical meter. If your system doesn't have these, Tesla's documentation says to get data from the Neurio. Solar-only installs tend to use Neurio, Powerwalls tend to use the Tesla meter.
References:
- https://energylibrary.tesla.com/docs/Public/EnergyStorage/Powerwall/General/MeteringGuide/en-us/GUID-932E78BF-6DFF-4CCA-9741-E4793E9F4314.html
- https://energylibrary.tesla.com/docs/Public/EnergyStorage/Powerwall/General/MeteringGuide/en-us/GUID-A46FB1D7-AEE5-4B66-99FF-39FE576F2B2D.html
This allowed me to get current data from my Neurios on my Tesla inverter solar-only setup.
> Use Neurio for TEDAPI data when Tesla Remote Meter is not present

- proxy/server.py
This was supposed to be removed by
https://github.com/jasonacox/pypowerwall/commit/59427dc9ef9e19cd5d2d80b9afd8a1802e162cbd but somehow it wasn't?
In any case, the "ensure api_base_url ends with a /" branch will never execute unless this is removed.
> Fix errant API base URL check.

- .github/workflows/test.yml
- pypowerwall/tests/test_powerwall.py
- pytest.ini
- test_requirements.txt
Before this PR, not all tests ran. Pytest wasn't finding them due to an over-specified test path search.
Additionally, we weren't measuring line and branch coverage. This fixes that. Upload to codecov as an easy way to see the coverage results in a browser. This should be free for public repos.
Finally, upgrade github actions plugins and make minor improvements to the test.yml workflow.
> Pytest now runs all tests. Also add line and branch coverage

- .github/workflows/test.yml
- proxy/server.py
- proxy/tests/test_do_get.py
- pytest.ini
Initial unit test, as simple as I could get it. Unfortunately, it does require some modifications to the proxy to get working.
First unit test chosen because it's easy and closed-scope: The stats endpoints.
Biggest problem: The code in the proxy is no longer fully compatible with Python 3.8: https://indhumathychelliah.com/2020/10/12/new-string-methods-to-remove-prefixes-and-suffixes-in-python-3-9/
The `do_GET` handler uses `removeprefix`. This was already merged, so the proxy has been broken on 3.8 for a while. This tells me that we can justifiably drop it. Clearly nobody was actually using this with Python 3.8 any longer, otherwise we'd have gotten bug reports.
> Add initial unit tests to the proxy

- .github/workflows/simtest.yml
The pwsimulator image comes from the root repository, not the forked ones (usually). Modify the workflow so that when people submit PRs, they don't get annoying emails telling them that the simulator failed because it couldn't find the image stored in their repository.
- Upgrade versions.
- Move coverage to using the latest Python.
- More granular steps rather than larger ones.
- Add a step to wait for the simulator server to initialize
- Collect logs on failure.
> Fix lookup of pwsimulator image.

- RELEASE.md
- proxy/Dockerfile
- proxy/Dockerfile.beta
- proxy/RELEASE.md
- proxy/server.py
Added curl to Dockerfiles to use in healthchecks instead of wget to fix [issue ](https://github.com/jasonacox/Powerwall-Dashboard/issues/693)
> Add curl to Dockerfiles to use in healthchecks instead of wget
