- README.md
- pypowerwall/__init__.py
- Closes #5
- Added pwcacheexpire to __init__ to allow adjustment of the cache time
- Added timeout to __init__ to allow adjustment of the http timeout
- added force to pol() to bypass the cache regardless of the timeout
- moved the check for the vitals to after the cache check (minor optimization)
> Updates to __init__ and poll()

- README.md
- pypowerwall/__init__.py
- Closes #7
- add function grid_status() that matches the API call
> Implement call to /api/system_status/grid_status

- README.md
- pypowerwall/__init__.py
- Fixes #6
- implements call to /api/system_status with system_status()
- implements battery_blocks() by merging data from calls to
system_status() and vitals()
> Implement system_status() and battery_blocks()

- proxy/server.py
Add shebang to allow us to:
`chmod +x server.py;./server.py`
> Add shebang for direct execution

- README.md
Added VFCheck_RoCoF alert from PVAC
> Additional alert message

- proxy/README.md
- proxy/server.py
Fix for the issue described in #31
> Fix Cache-Control no-cache header and allow for setting max-age, fixes #31

- tools/tessolarcharge.py
Stability fix- don't stop charging a vehicle that is not charging. Tested and runs for days across multiple plug/unplug sessions, nights without charging, etc.
> Fix tessolarcharge.py script

- README.md
From:
"PVAC":{
"PVAC_InvState": "INV_Faulted",
"PVAC_State": "PVAC_Faulted",
"alerts": [
"PVAC_a028_inv_K2_relay_welded",
"PVAC_a043_fan_speed_mismatch_detected"
]
}
> Added two PVAC Alerts

- README.md
Added firmware version 23.28.1 fa0c1ad0 (Rolled out to a Powerwall+ 11-Sep-2023)
>  Added fw 23.28.1 to README.md

- proxy/RELEASE.md
- proxy/server.py
Fix jasonacox/Powerwall-Dashboard#353
> Exit proxy gracefully with SIGTERM

- .gitignore
- RELEASE.md
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/cloud/pypowerwall_cloud.py
* Fix bug with setup for certain Solar Only systems where setup process fails. Identified by @hulkster in https://github.com/jasonacox/Powerwall-Dashboard/discussions/475
> v0.8.5 - Fix bug with setup for certain Solar Only systems

- RELEASE.md
- proxy/requirements.txt
- pypowerwall/__init__.py
- pypowerwall/fleetapi/fleetapi.py
- tools/fleetapi/README.md
* Fix FleetAPI setup script as raised in https://github.com/jasonacox/pypowerwall/issues/98.
* Update FleetAPI documentation and CLI usage.
Closes #98
> Fix FleetAPI Setup

- .github/workflows/pylint.yml
- .pylintrc
- RELEASE.md
- proxy/RELEASE.md
- proxy/requirements.txt
- proxy/server.py
- proxy/transform.py
- pypowerwall/__init__.py
- pypowerwall/__main__.py
- pypowerwall/cloud/pypowerwall_cloud.py
- pypowerwall/fleetapi/__main__.py
- pypowerwall/fleetapi/fleetapi.py
- pypowerwall/fleetapi/pypowerwall_fleetapi.py
- pypowerwall/pypowerwall_base.py
- pypowerwall/scan.py
- pypowerwall/tedapi/__init__.py
- pypowerwall/tedapi/__main__.py
- pypowerwall/tedapi/pypowerwall_tedapi.py
* TEDAPI get_reserve() fix to address unscaled results.
* Address pyLint Cleanup of Code.
* Proxy: Command mode error handling.
* Cloud Mode: Fix logic for selecting FleetAPI mode
* Add request timeout settings to FleetAPI and TEDAPI calls.
> Address pyLint cleanup and minor bug fixes

- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
* Fix bug in TEDAPI vitals processor that was not pulling in all Neurio CTS data. Issue reported in https://github.com/jasonacox/Powerwall-Dashboard/discussions/578#discussioncomment-12034018 and tracked in https://github.com/jasonacox/pypowerwall/issues/136.
> Fix CTS data retrieval in TEDAPI vitals processor #136

- RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/tedapi/pypowerwall_tedapi.py
* Updated aggregates call to include site current (METER_X) and external PV inverter data in solar (METER_Y). 
* Reported in Issue #140.
Closes #140
> Update Aggregates API

- .github/workflows/simtest.yml
- .github/workflows/test.yml
- pypowerwall/tedapi/pypowerwall_tedapi.py
Fix for 
TypeError: PyPowerwallTEDAPI.vitals() got an unexpected keyword argument 'force'
> Fix kwargs bug

- API.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- RELEASE.md
- proxy/API.md
- proxy/HELP.md
- proxy/README.md
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
- pypowerwall/tedapi/pypowerwall_tedapi.py
- test_requirements.txt
Stage for v0.13.0
* Additional values /json endpoint by @erikgieseler in https://github.com/jasonacox/pypowerwall/pull/176
* Use Neurio for TEDAPI data when Tesla Remote Meter is not present by @Nexarian in https://github.com/jasonacox/pypowerwall/pull/157
* Initial simple unit test by @Nexarian in https://github.com/jasonacox/pypowerwall/pull/181
* Add connection pool to TEDAPI by @Nexarian in https://github.com/jasonacox/pypowerwall/pull/177
* Add METER_Z (Backup Switch) data to vitals and aggregates data - See https://github.com/jasonacox/Powerwall-Dashboard/discussions/629#discussioncomment-13284217
* Update and add documentation helps: contributor, conduct and API (python and proxy)
> Stage v0.13.0

- RELEASE.md
- proxy/RELEASE.md
- pypowerwall/__init__.py
- pypowerwall/tedapi/__init__.py
- pypowerwall/tedapi/pypowerwall_tedapi.py
* Fix missing battery_blocks data on PW3 with Multiple Powerwalls in Local Mode in https://github.com/jasonacox/pypowerwall/issues/131
> Update TEDAPI to pull battery blocks from vitals for PW3 Systems

- proxy/API.md
- proxy/README.md
- proxy/RELEASE.md
- proxy/server.py
This pull request introduces enhancements to the `pyPowerwall Proxy` to improve network robustness, error handling, and operational reliability. The changes include advanced connection health monitoring, fail-fast and graceful degradation modes, specialized handling for weak network environments, and enhanced global error handling.
* **Connection Health Monitoring**: Tracks connection status, error/success counts, and provides health status via `/health` endpoint. Includes automatic degraded mode and recovery mechanisms. (`PW_HEALTH_CHECK=yes`, default enabled)
* **Fail-Fast Mode**: Reduces timeout delays by immediately returning cached or empty data during degraded states, optimizing performance for rapid polling scenarios. (`PW_FAIL_FAST=yes`, default disabled)
* **Graceful …
> Proxy Update t76 - Network Health Monitoring

- README.md
- RELEASE.md
- proxy/Dockerfile
- proxy/Dockerfile.beta
- proxy/beta.txt
- pypowerwall/__init__.py
- pypowerwall/fleetapi/__main__.py
- pypowerwall/fleetapi/fleetapi.py
- requirements.txt
- setup.py
This pull request introduces enhancements, bug fixes, and dependency updates for the `pypowerwall` project. Key changes include improved error handling in the FleetAPI CLI, support for a new operational mode, updated dependencies to address compatibility issues, and modifications to the Docker setup for better build efficiency.
* Improved error handling for commands like `sites`, `status`, `info`, `getmode`, and `getreserve`, providing clearer error messages and exiting gracefully on API or authentication failures. [[1]](diffhunk://#diff-e7a30dce70da3c402e645aaab9c2f53e591f092390f33b8aaaa77c581fa87c5dR109-R126) [[2]](diffhunk://#diff-e7a30dce70da3c402e645aaab9c2f53e591f092390f33b8aaaa77c581fa87c5dR137-R139) [[3]](diffhunk://#diff-e7a30dce70da3c402e645aaab9c2f53e591f092390f33b8aaaa77c581fa8 …
> Pin TeslaPy and Fix FleetAPI CLI

- RELEASE.md
- pypowerwall/__init__.py
This pull request updates the `pyPowerwall` library to version `0.14.0` and includes changes to improve functionality and address specific issues with TeslaPy and FleetAPI.
* [`RELEASE.md`](diffhunk://#diff-2b1b69303b927a484e02c7fad9fc87d0d3ff0dc22ae1da0ecd0dc935d922a23cL3-R5): Updated release notes to reflect version `v0.14.0`. TeslaPy code patch is now embedded directly into `pyPowerwall` to resolve issues with setting Powerwall Mode, and FleetAPI CLI improvements include better error handling and clearer output.
* [`pypowerwall/__init__.py`](diffhunk://#diff-c3c2ae850adc019cf48d1243c8e21c1333dcfd608e37abd642c9a7427c246e62L91-R91): Updated the `version_tuple` to `(0, 14, 0)` to align with the new release version.…API fixes
> v0.14.0 Release Prep

- .gitignore
- RELEASE.md
- proxy/RELEASE.md
- proxy/requirements.txt
- proxy/server.py
- pypowerwall/__init__.py
- pypowerwall/tests/unit/test_parse_version.py
- pypowerwall/tests/unit/test_powerwall_core.py
This pull request updates `pyPowerwall` and its proxy to version 0.14.1, focusing on improving test coverage, error logging, and robustness in handling battery data. The main changes include expanded unit tests, a stub client for deterministic testing, improved error messages in the proxy, and a fix for a potential KeyError in the `battery_blocks()` method.
**Test Coverage & Reliability Improvements**
* Added extensive unit tests for version parsing and core Powerwall methods, including polling, power aggregation, grid status (numeric/json), alerts fallback, operation validation, reserve/mode helpers, temperature readings, and site name retrieval. A stub client is introduced for deterministic, offline execution in tests. [[1]](diffhunk://#diff-2b1b69303b927a484e02c7fad9fc87d0d3ff0dc22ae1da …
> Enhance error logging and add unit tests
